---
apiVersion: collectors.grafana.com/v1alpha1
kind: Alloy
metadata:
  name: alloy-singleton
  namespace: monitoring
  annotations:
    helm.sdk.operatorframework.io/uninstall-wait: "true"
spec:
  controller:
    type: deployment
    replicas: 1
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: remote-config-credentials
            key: password
      - name: CLUSTER_NAME
        value: fm-test-cluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace

    configMap:
      content: |
        remote.kubernetes.secret "remote_config_credentials" {
          name = "remote-config-credentials"
          namespace = sys.env("NAMESPACE")
        }
        
        remotecfg {
          id = string.format("%s-%s-singleton", sys.env("CLUSTER_NAME"), sys.env("NAMESPACE"))
          url = convert.nonsensitive(remote.kubernetes.secret.remote_config_credentials.data["url"])
          basic_auth {
            username = convert.nonsensitive(remote.kubernetes.secret.remote_config_credentials.data["username"])
            password = remote.kubernetes.secret.remote_config_credentials.data["password"]
          }
          poll_frequency = "1m"
          attributes = {
            "platform" = "kubernetes",
            "cluster" = sys.env("CLUSTER_NAME"),
            "namespace" = sys.env("NAMESPACE"),
            "purpose" = "singleton",
          }
        }
