pipelines:
  - name: kubernetes_metrics_beyla_surveyor
    file: beyla-surveyor.alloy
    matchers:
      - platform=kubernetes
      - beyla-surveyor=true

  - name: kubernetes_metrics_kubelet
    file: kubelet.alloy
    matchers:
      - platform=kubernetes
      - kubelet-scraper=true

  - name: kubernetes_metrics_cadvisor
    file: cadvisor.alloy
    matchers:
      - platform=kubernetes
      - cadvisor-scraper=true

  - name: kubernetes_metrics_kepler
    file: kepler.alloy
    matchers:
      - platform=kubernetes
      - kepler-scraper=true

  - name: kubernetes_metrics_kube_state_metrics
    file: kube-state-metrics.alloy
    matchers:
      - platform=kubernetes
      - kube-state-metrics-scraper=true

  - name: kubernetes_metrics_node_exporter
    file: node-exporter.alloy
    matchers:
      - platform=kubernetes
      - node-exporter-scraper=true

  - name: kubernetes_metrics_opencost
    file: opencost.alloy
    matchers:
      - platform=kubernetes
      - opencost-scraper=true

  - name: kubernetes_logs_journald
    file: journald-logs.alloy
    matchers:
      - platform=kubernetes
      - journald-logs-gatherer=true

  - name: kubernetes_logs_pod_filesystem
    file: filesystem-pod-logs.alloy
    matchers:
      - platform=kubernetes
      - filesystem-pod-logs-gatherer=true

  - name: kubernetes_logs_cluster_events
    file: cluster-events.alloy
    matchers:
      - platform=kubernetes
      - cluster-events-gatherer=true
